import React,{useEffect,useRef,useState,useCallback} from 'react';
import {Server,RefreshCw,Search,ArrowUpRight,AlertCircle,X} from 'lucide-react';
import {Metrics,Dependency,ServiceRow,Group,StopDialog} from './components';
export default function App(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[pending,setPending]=useState(null),[refreshing,setRefreshing]=useState(false),[confirm,setConfirm]=useState(null),[gpuOpen,setGpuOpen]=useState(true),[dockerOpen,setDockerOpen]=useState(true),[stale,setStale]=useState(false);
 const alive=useRef(true),loading=useRef(false),token=useRef('');
 const load=useCallback(async(manual=false)=>{if(loading.current)return;loading.current=true;if(manual)setRefreshing(true);try{const r=await fetch('/api/state',{cache:'no-store'});const body=await r.json();if(!r.ok)throw Error(body.error||'No se pudo actualizar el estado.');if(alive.current){token.current=body.csrfToken;setData(body);setStale(false);if(manual)setError('')}}catch(e){if(alive.current){setStale(true);setError(e.message||'Conexión perdida. Vuelve a abrir el panel si tu sesión ha caducado.')}}finally{loading.current=false;if(alive.current)setRefreshing(false)}},[]);
 useEffect(()=>{alive.current=true;load();const t=setInterval(()=>{if(!document.hidden)load()},5000);return()=>{alive.current=false;clearInterval(t)}},[load]);
 useEffect(()=>{if(!confirm)return;const handler=e=>{if(e.key==='Escape')setConfirm(null)};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler)},[confirm]);
 const execute=async s=>{setConfirm(null);setPending({id:s.id,action:s.running?"stop":"start"});setError('');setNotice('');try{const r=await fetch(`/api/services/${s.id}/${s.running?'stop':'start'}`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':token.current},body:'{}'});const body=await r.json();if(!r.ok)throw Error(body.error||'La operación no se completó.');setNotice(`${s.name}: ${s.running?'apagado':'arranque solicitado'}.`)}catch(e){setError(e.message||'La operación no se completó.')}finally{setPending(null);await load()}};
 const action=s=>{if(s.running&&['minecraft','browser','transmission'].includes(s.id))setConfirm(s);else execute(s)};
 const rows=(data?.services||[]).filter(s=>(filter==='all'||(filter==='on'?s.running:!s.running))&&`${s.name} ${s.description}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const busy=!!pending||data?.busy||stale;const groupRows=g=>rows.filter(s=>s.group===g);const row=(s,indent=true)=><ServiceRow key={s.id} service={s} pending={pending} busy={busy} onAction={action} dependencies={{...data.dependencies,gotify:{name:'Gotify',state:data.services.find(s=>s.id==='gotify')?.state,message:'Se inicia antes que iGotify.'}}} indent={indent}/>;
 return <><header className="topbar"><div className="topbar-inner"><a className="brand" href="/"><Server size={25}/><span>Beachlab</span></a><a className="account" href="https://auth.beachlab.org/if/user/" target="_blank" rel="noopener noreferrer"><span className="avatar">{(data?.user||'F')[0].toUpperCase()}</span><span>{data?.user||'Fran'}</span><ArrowUpRight size={15}/></a></div></header>
 <main><div className="heading"><div><h1>Servicios</h1><p>Controla lo que está en marcha.</p></div><button className="primary" onClick={()=>load(true)} disabled={refreshing}><RefreshCw size={17} className={refreshing?'spin':''}/>Actualizar</button></div>
 <Metrics data={data}/><div className="toolbar"><label className="search"><Search size={19}/><input type="search" placeholder="Buscar servicio…" value={search} onChange={e=>setSearch(e.target.value)} aria-label="Buscar servicio"/></label><div className="filters" role="group" aria-label="Filtrar servicios">{[['all','Todos'],['on','En marcha'],['off','Apagados']].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)} className={filter===value?'selected':''}>{label}</button>)}</div></div>
 {error&&<div className="alert error" role="alert"><AlertCircle size={18}/><span>{error}</span><button onClick={()=>setError('')} aria-label="Cerrar aviso"><X size={17}/></button></div>}{notice&&<div className="alert success" role="status">{notice}</div>}
 {!data?<div className="empty">Consultando los servicios del servidor…</div>:<>{groupRows('ai').length>0&&<Group title="Inteligencia artificial"><Dependency item={data.dependencies.egpu} expanded={gpuOpen} onToggle={()=>setGpuOpen(!gpuOpen)}/>{gpuOpen&&groupRows('ai').map(s=>row(s))}</Group>}
 {groupRows('apps').length>0&&<Group title="Aplicaciones">{groupRows('apps').some(s=>s.dependencies.includes('docker'))&&<><Dependency item={data.dependencies.docker} expanded={dockerOpen} onToggle={()=>setDockerOpen(!dockerOpen)}/>{dockerOpen&&groupRows('apps').filter(s=>s.dependencies.includes('docker')).map(s=>row(s))}</>}{groupRows('apps').filter(s=>!s.dependencies.includes('docker')).map(s=>row(s,false))}</Group>}
 {groupRows('games').length>0&&<Group title="Juegos">{groupRows('games').map(s=>row(s,false))}</Group>}
 {groupRows('monitoring').length>0&&<Group title="Monitorización">{groupRows('monitoring').map(s=>row(s,false))}</Group>}
 {!rows.length&&<div className="empty">No hay servicios que coincidan con este filtro.</div>}</>}
 <footer><i className={stale?'stale':''}/>{stale?'Sin conexión · controles desactivados':data?`Estado actualizado · ${new Date(data.updatedAt*1000).toLocaleTimeString('es-ES')}`:'Conectando…'}<span>Los cambios se aplican ahora, no al inicio del servidor.</span></footer>
 </main>{confirm&&<StopDialog service={confirm} onClose={()=>setConfirm(null)} onConfirm={()=>execute(confirm)}/>}</>;
}
