import React,{useState} from 'react';
import {Server,Cpu,MemoryStick,Database,Image,AudioLines,Mic,FileText,Download,Monitor,Link,Box,ChartNoAxesCombined,Bell,Smartphone,Map,ArrowUpRight,ChevronDown,LoaderCircle,ShieldCheck,Copy,Check} from 'lucide-react';
const icons={image:Image,audio:AudioLines,mic:Mic,file:FileText,download:Download,monitor:Monitor,link:Link,box:Box,chart:ChartNoAxesCombined,bell:Bell,phone:Smartphone,map:Map};
export const labels={active:'En marcha',inactive:'Apagado',failed:'Error',degraded:'Revisar salud',activating:'Arrancando',deactivating:'Deteniendo',reloading:'Actualizando',unknown:'Sin datos'};
export function Status({state,label}){return <span className={`status ${state}`}><i/>{label||labels[state]||state}</span>}
function size(n){return `${(n/1024**3).toLocaleString('es-ES',{maximumFractionDigits:1})} GB`}
export function Metrics({data}){const m=data?.metrics;return <section className="metrics" aria-label="Estado del servidor">{[
 [Server,data?.host||'thebeachlab','Servidor local'],[Cpu,'Carga CPU',m?`${m.load.toLocaleString('es-ES')} / ${m.cpus} núcleos`:'—'],[MemoryStick,'Memoria',m?`${size(m.memoryUsed)} / ${size(m.memoryTotal)}`:'—'],[Database,'Disco',m?`${size(m.diskUsed)} / ${size(m.diskTotal)}`:'—']
].map(([Icon,title,value],i)=><div className={i===0?'host-metric':'metric'} key={title}><Icon size={i===0?30:26}/><div><span>{title}</span><strong>{value}</strong></div></div>)}</section>}
export function Dependency({item,onToggle,expanded}){return <button className="dependency" onClick={onToggle} aria-expanded={expanded}><ChevronDown size={17} className={expanded?'':'closed'}/>{item.id==='egpu'?<Cpu size={23}/>:<Box size={23}/>}<strong>{item.name}</strong><Status state={item.state} label={item.state==='active'?'Disponible':undefined}/><span className="dependency-message">{item.message}</span></button>}
export function ServiceRow({service:s,pending,busy,onAction,dependencies,indent=true}){
 const [details,setDetails]=useState(false),[copied,setCopied]=useState(false);const Icon=icons[s.icon]||Server;
 const blocked=!s.running&&s.blocked;const processing=pending?.id===s.id||['activating','deactivating'].includes(s.state);
 const copy=async()=>{try{await navigator.clipboard.writeText(s.connection);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setCopied(false)}};
 return <div className={`service-wrap ${indent?'nested':''}`}><div className="service-row">
  <div className="service-name"><Icon size={21}/><strong>{s.name}</strong></div>
  <div className="service-description">{s.description}</div>
  <Status state={pending?.id===s.id?(pending.action==='stop'?'deactivating':'activating'):s.state}/>
  <div className="toggle-wrap"><button className={`toggle ${s.running?'on':''}`} role="switch" aria-checked={s.running} aria-label={`${s.running?'Apagar':'Encender'} ${s.name}`} disabled={busy||!!blocked||!s.installed} title={blocked||`${s.running?'Apagar':'Encender'} ${s.name}`} onClick={()=>onAction(s)}>{processing?<LoaderCircle size={17} className="spin"/>:<span/>}</button></div>
  <div className="row-links">{s.dependencies.filter(x=>!['docker','egpu'].includes(x)).length>0&&<button className="dependency-link" aria-label={`Dependencias de ${s.name}`} aria-expanded={details} onClick={()=>setDetails(!details)}><Link size={15}/><span>{s.dependencies.includes('vpn')?'VPN integrada':s.dependencies.includes('firewall')?'Cortafuegos':'Gotify'}</span></button>}
  {s.url?<a className="open-button" href={s.url} target="_blank" rel="noopener noreferrer">Abrir<ArrowUpRight size={17}/></a>:s.connection?<button className="connection" onClick={copy} title="Copiar dirección">{copied?<Check size={15}/>:<Copy size={15}/>}<span>{s.connection}</span></button>:<span className="no-link"/>}</div>
 </div>{s.state==='degraded'&&<p className="blocked-message">El contenedor sigue activo, pero falla su comprobación de salud. Revisa la conectividad y sus dependencias.</p>}{blocked&&<p className="blocked-message">{blocked}</p>}{details&&<div className="dependency-details">{s.dependencies.filter(x=>!['docker','egpu'].includes(x)).map(id=>{const d=dependencies[id]||{name:'Gotify',state:'unknown',message:'Se inicia antes que iGotify.'};return <div key={id}><ShieldCheck size={16}/><strong>{d.name}</strong><Status state={d.state}/><span>{d.message}</span></div>})}</div>}</div>
}
export function Group({title,children}){const [open,setOpen]=useState(true);return <section className="group"><h2><button aria-expanded={open} onClick={()=>setOpen(!open)}><ChevronDown size={19} className={open?'':'closed'}/>{title}</button></h2>{open&&children}</section>}
export function StopDialog({service,onClose,onConfirm}){return <div className="modal-backdrop" onClick={onClose}><section role="dialog" aria-modal="true" aria-labelledby="stop-title" className="dialog" onClick={e=>e.stopPropagation()}><h2 id="stop-title">Apagar {service.name}</h2><p>{service.id==='minecraft'?'Los jugadores se desconectarán. El servidor guardará el mundo antes de detenerse.':service.id==='transmission'?'Las descargas se pausarán y se cerrará la conexión VPN del contenedor.':'La sesión del navegador se cerrará. Las descargas o tareas en curso podrían interrumpirse.'}</p><div><button autoFocus className="secondary" onClick={onClose}>Cancelar</button><button className="danger" onClick={onConfirm}>Apagar servicio</button></div></section></div>}
