# Bootstrap certificate using certbot certonly --webroot -w /var/www/letsencrypt.
server {
    listen 80;
    listen [::]:80;
    server_name auth.beachlab.org;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }
    location / { return 301 https://auth.beachlab.org$request_uri; }
}
