# https://docs.goauthentik.io/install-config/reverse-proxy/ (2026-09-14)
server {
    listen 80;
    listen [::]:80;
    server_name auth.beachlab.org;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }
    location / { return 301 https://auth.beachlab.org$request_uri; }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name auth.beachlab.org;
    ssl_certificate /etc/letsencrypt/live/auth.beachlab.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/auth.beachlab.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    client_max_body_size 20m;
    location / {
        proxy_pass http://127.0.0.1:19000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffers 8 16k;
        proxy_buffer_size 32k;
    }
}
