-- Additive migration: retains all historical readings and existing view grants.
BEGIN;
SET LOCAL lock_timeout = '5s';
ALTER TABLE public.bluetti_stats ADD COLUMN IF NOT EXISTS field_received_at jsonb;
CREATE OR REPLACE VIEW public.bluetti_latest AS
SELECT DISTINCT ON (device_id) "time",
    device_id,
    battery_percent,
    dc_input_power,
    ac_input_power,
    ac_output_power,
    dc_output_power,
    power_generation,
    ac_output_on,
    dc_output_on,
    pack_details1,
    pack_details2,
    co2_ppm,
    temperature_c,
    humidity_pct,
    pressure_hpa,
    starlink_state,
    starlink_downlink_mbps,
    starlink_uplink_mbps,
    starlink_ping_ms,
    starlink_ping_drop_rate,
    starlink_uptime_s,
    starlink_obstructed,
    starlink_obstruction_pct,
    starlink_gps_sats,
    starlink_country,
    starlink_ping_ms_avg,
    starlink_azimuth_deg,
    starlink_elevation_deg,
    starlink_tilt_deg,
    starlink_alerts,
    gps_lat,
    gps_lon,
    gps_speed_kmh,
    gps_altitude_m,
    gps_satellites,
    gps_fix,
    heading_deg,
    altitude_m,
    baro_altitude_m,
    imu_pitch_deg,
    imu_roll_deg,
    imu_yaw_rate_dps,
    obd_rpm,
    obd_speed_kmh,
    obd_throttle_pct,
    obd_engine_load_pct,
    obd_boost_kpa,
    obd_coolant_temp_c,
    obd_intake_temp_c,
    obd_oil_temp_c,
    obd_fuel_level_pct,
    obd_fuel_rail_pressure_kpa,
    obd_maf_gps,
    obd_runtime_s,
    obd_voltage_v,
    obd_dtc_count,
    obd_connected,
    field_received_at
   FROM bluetti_stats
  ORDER BY device_id, "time" DESC;
NOTIFY pgrst, 'reload schema';
COMMIT;
